# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_data_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from kategori import kategori
from barang import barang
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",  
    database="my_oop_database"
)
class Ui_MainWindow(object):
    def delete_barang(self):
        id = self.ID.text()
        barang.delete_data(id)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tambahdatabarang = QtWidgets.QLabel(self.centralwidget)
        self.tambahdatabarang.setGeometry(QtCore.QRect(80, 50, 241, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tambahdatabarang.sizePolicy().hasHeightForWidth())
        self.tambahdatabarang.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tambahdatabarang.setFont(font)
        self.tambahdatabarang.setAlignment(QtCore.Qt.AlignCenter)
        self.tambahdatabarang.setObjectName("tambahdatabarang")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(50, 410, 305, 28))
        self.delete_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.delete_2.setStyleSheet("#simpan {\n"
"    background-color: #0078d7; \n"
"    color: white;           \n"
"    border-radius: 10px;        \n"
"    border: none;                \n"
"    padding: 6px 15px;          \n"
"}\n"
"\n"
"#simpan:hover {\n"
"    background-color: #005fa3; \n"
"}\n"
"")
        self.delete_2.setObjectName("delete_2")
        self.cari = QtWidgets.QPushButton(self.centralwidget)
        self.cari.setGeometry(QtCore.QRect(290, 134, 71, 28))
        self.cari.setStyleSheet("#cari {\n"
"    background-color: #0078d7; \n"
"    color: white;           \n"
"    border-radius: 10px;        \n"
"    border: none;                \n"
"    padding: 6px 15px;          \n"
"}")
        self.cari.setObjectName("cari")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 130, 361, 154))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 5, 0, 0)
        self.formLayout.setHorizontalSpacing(7)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.iDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.iDLabel.setObjectName("iDLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.ID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ID.setMinimumSize(QtCore.QSize(200, 25))
        self.ID.setMaximumSize(QtCore.QSize(200, 25))
        self.ID.setObjectName("ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ID)
        self.namaLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.namaLabel.setObjectName("namaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.namaLabel)
        self.namaWidget = QtWidgets.QWidget(self.formLayoutWidget)
        self.namaWidget.setObjectName("namaWidget")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.namaWidget)
        self.stockLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.stockLabel.setObjectName("stockLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stockLabel)
        self.Kategori = QtWidgets.QWidget(self.formLayoutWidget)
        self.Kategori.setObjectName("Kategori")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Kategori)
        self.hargaLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hargaLabel.setObjectName("hargaLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hargaLabel)
        self.hargaWidget = QtWidgets.QWidget(self.formLayoutWidget)
        self.hargaWidget.setObjectName("hargaWidget")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hargaWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.delete_2.clicked.connect(self.delete_barang)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tambahdatabarang.setText(_translate("MainWindow", "Delete data barang"))
        self.delete_2.setText(_translate("MainWindow", "Delete"))
        self.cari.setText(_translate("MainWindow", "Cari"))
        self.iDLabel.setText(_translate("MainWindow", "ID"))
        self.namaLabel.setText(_translate("MainWindow", "Nama"))
        self.stockLabel.setText(_translate("MainWindow", "Stock"))
        self.hargaLabel.setText(_translate("MainWindow", "Harga"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
