# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import form_login as fl
import buat_user as add
import delete_user as dell
import update_user as ed
import data_user as ld
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def lihat_data(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ld.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def insert_data(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = add.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def update_data(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ed.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def delete_data(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dell.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def logout_kembali(self):
        self.loginWindow = QtWidgets.QMainWindow()
        self.loginUI = fl.Ui_MainWindow()
        self.loginUI.setupUi(self.loginWindow)
        self.loginWindow.show()
        self.MainWindow.close()
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        MainWindow.setMinimumSize(QtCore.QSize(700, 700))
        MainWindow.setMaximumSize(QtCore.QSize(700, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 50, 461, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 210, 681, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.insert = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert.sizePolicy().hasHeightForWidth())
        self.insert.setSizePolicy(sizePolicy)
        self.insert.setMinimumSize(QtCore.QSize(150, 150))
        self.insert.setMaximumSize(QtCore.QSize(150, 150))
        self.insert.setStyleSheet("#insert{\n"
"    background-color: #0078d7;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    border: none;\n"
"    padding: 6px 15px;\n"
"}\n"
"#insert:hover{\n"
"    background-color: #005fa3;\n"
"\n"
"}")
        self.insert.setObjectName("insert")
        self.gridLayout.addWidget(self.insert, 0, 0, 1, 1)
        self.update = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update.sizePolicy().hasHeightForWidth())
        self.update.setSizePolicy(sizePolicy)
        self.update.setMinimumSize(QtCore.QSize(150, 150))
        self.update.setMaximumSize(QtCore.QSize(150, 150))
        self.update.setStyleSheet("#update{\n"
"    background-color: #0078d7;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    border: none;\n"
"    padding: 6px 15px;\n"
"}\n"
"#update:hover{\n"
"    background-color: #005fa3;\n"
"\n"
"}")
        self.update.setObjectName("update")
        self.gridLayout.addWidget(self.update, 0, 1, 1, 1)
        self.delete_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_2.sizePolicy().hasHeightForWidth())
        self.delete_2.setSizePolicy(sizePolicy)
        self.delete_2.setMinimumSize(QtCore.QSize(150, 150))
        self.delete_2.setMaximumSize(QtCore.QSize(150, 150))
        self.delete_2.setStyleSheet("#delete_2{\n"
"    background-color: #0078d7;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    border: none;\n"
"    padding: 6px 15px;\n"
"}\n"
"#delete_2:hover{\n"
"    background-color: #005fa3;\n"
"\n"
"}")
        self.delete_2.setObjectName("delete_2")
        self.gridLayout.addWidget(self.delete_2, 1, 0, 1, 1)
        self.lihat = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lihat.sizePolicy().hasHeightForWidth())
        self.lihat.setSizePolicy(sizePolicy)
        self.lihat.setMinimumSize(QtCore.QSize(150, 150))
        self.lihat.setMaximumSize(QtCore.QSize(150, 150))
        self.lihat.setStyleSheet("#lihat{\n"
"    background-color: #0078d7;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    border: none;\n"
"    padding: 6px 15px;\n"
"}\n"
"#lihat:hover{\n"
"    background-color: #005fa3;\n"
"\n"
"}")
        self.lihat.setObjectName("lihat")
        self.gridLayout.addWidget(self.lihat, 1, 1, 1, 1)
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(20, 10, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout.sizePolicy().hasHeightForWidth())
        self.logout.setSizePolicy(sizePolicy)
        self.logout.setStyleSheet("#logout{\n"
"    background-color: #0078d7;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"}\n"
"#logout:hover{\n"
"    background-color: #005fa3;\n"
"\n"
"}")
        self.logout.setObjectName("logout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # fungsi buton
        self.logout.clicked.connect(self.logout_kembali)
        self.insert.clicked.connect(self.insert_data)
        self.update.clicked.connect(self.update_data)
        self.delete_2.clicked.connect(self.delete_data)
        self.lihat.clicked.connect(self.lihat_data)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DASHBOARD ADMIN"))
        self.insert.setText(_translate("MainWindow", "Insert Data Users"))
        self.update.setText(_translate("MainWindow", "Update  Data Users"))
        self.delete_2.setText(_translate("MainWindow", "Delete Data Users"))
        self.lihat.setText(_translate("MainWindow", "Lihat Data Users"))
        self.logout.setText(_translate("MainWindow", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
