# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import dashboard_admin as ad
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def kembali_db(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ad.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.datauser = QtWidgets.QTableWidget(self.centralwidget)
        self.datauser.setGeometry(QtCore.QRect(25, 170, 751, 301))
        self.datauser.setObjectName("datauser")
        self.datauser.setColumnCount(3)
        self.datauser.setRowCount(0)
        self.datauser.setHorizontalHeaderLabels(["Nama", "Username", "Role"])
        self.datauser.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.datauser.horizontalHeader().setStretchLastSection(True)
        self.datauser.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        self.kembali = QtWidgets.QPushButton(self.centralwidget)
        self.kembali.setGeometry(QtCore.QRect(350, 500, 93, 28))
        self.kembali.setStyleSheet("#kembali {\n"
            "background-color: #0078d7;\n"
            "color: white;\n"
            "border-radius: 10px;\n"
            "border: none;\n"
            "padding: 6px 15px;\n"
        "}\n"
        "#kembali:hover {\n"
            "background-color: #005fa3;\n"
        "}")
        self.kembali.setObjectName("kembali")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.load_user_data()
        self.kembali.clicked.connect(self.kembali_db)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Data User"))
        self.kembali.setText(_translate("MainWindow", "Kembali"))

    def load_user_data(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="my_oop_database"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT nama, username, level FROM user")
            result = mycursor.fetchall()

            self.datauser.setRowCount(len(result))
            for i, row in enumerate(result):
                for j, value in enumerate(row):
                    item = QtWidgets.QTableWidgetItem(str(value))
                    item.setTextAlignment(QtCore.Qt.AlignCenter)
                    self.datauser.setItem(i, j, item)

        except mysql.connector.Error as e:
            print("Gagal mengambil data user:", e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
