# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from user import user
from role import role
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def delete_usr(self):
        username = self.usn.text()
        if not username:
            QtWidgets.QMessageBox.warning(None, "Gagal", "Username tidak boleh kosong.")
            return
        confirm = QtWidgets.QMessageBox.question(None, "Konfirmasi", f"Yakin ingin menghapus user '{username}'?",
                                                QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        if confirm == QtWidgets.QMessageBox.Yes:
            user.hapus_user(username)
            QtWidgets.QMessageBox.information(None, "Berhasil", f"User '{username}' berhasil dihapus.")
            self.nama.clear()
            self.usn.clear()
            self.pw.clear()
            self.role.setCurrentIndex(0)

    def cari_data(self):
        username = self.cariline.text()
        data = user.cari_user(username)
        if data:
            self.nama.setText(data[0])
            self.usn.setText(username)
            self.pw.setText(data[1])
            self.role.addItems(role.select_data())
        else:
            QtWidgets.QMessageBox.warning(None, "Tidak Ditemukan", f"User '{username}' tidak ditemukan.")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 451)
        MainWindow.setMinimumSize(QtCore.QSize(450, 451))
        MainWindow.setMaximumSize(QtCore.QSize(450, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 50, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 210, 391, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.namaLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.namaLabel.setObjectName("namaLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.namaLabel)
        self.nama = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nama.setObjectName("nama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nama)
        self.usernameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usn = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usn.setObjectName("usn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.usn)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.pw = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pw.setObjectName("pw")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pw)
        self.roleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.role = QtWidgets.QComboBox(self.formLayoutWidget)
        self.role.setObjectName("role")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.role)
        self.cariline = QtWidgets.QLineEdit(self.centralwidget)
        self.cariline.setGeometry(QtCore.QRect(30, 180, 131, 22))
        self.cariline.setObjectName("cariline")
        self.cari = QtWidgets.QPushButton(self.centralwidget)
        self.cari.setGeometry(QtCore.QRect(180, 180, 70, 22))
        self.cari.setObjectName("cari")
        self.kembali = QtWidgets.QPushButton(self.centralwidget)
        self.kembali.setGeometry(QtCore.QRect(180, 390, 93, 28))
        self.kembali.setObjectName("kembali")
        self.hapus = QtWidgets.QPushButton(self.centralwidget)
        self.hapus.setGeometry(QtCore.QRect(260, 180, 70, 22))
        self.hapus.setObjectName("hapus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.cari.clicked.connect(self.cari_data)
        self.hapus.clicked.connect(self.delete_usr)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Delete User"))
        self.namaLabel.setText(_translate("MainWindow", "Nama"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.roleLabel.setText(_translate("MainWindow", "Role"))
        self.cari.setText(_translate("MainWindow", "Cari"))
        self.kembali.setText(_translate("MainWindow", "Kembali"))
        self.hapus.setText(_translate("MainWindow", "hapus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
