# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_data_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from kategori import kategori
from barang import barang
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",  
    database="my_oop_database"
)
class Ui_MainWindow(object):
    def delete_barang(self):
        id = self.ID.text()
        barang.delete_data(id)
    def cari_data(self):
        id = self.ID.text()
        data = barang.get_data_by_id(id)
        Nama=data[1]
        Stock=data[2]
        Harga=data[3]
        Kategori=data[4]
        self.namalabel.setText(str(Nama))
        self.stockLabel.setText(str(Stock))
        self.hargalabel.setText(str(Harga))
        self.kategoriLabel.setText(str(Kategori))
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tambahdatabarang = QtWidgets.QLabel(self.centralwidget)
        self.tambahdatabarang.setGeometry(QtCore.QRect(80, 50, 241, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tambahdatabarang.sizePolicy().hasHeightForWidth())
        self.tambahdatabarang.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tambahdatabarang.setFont(font)
        self.tambahdatabarang.setAlignment(QtCore.Qt.AlignCenter)
        self.tambahdatabarang.setObjectName("tambahdatabarang")
        self.delete = QtWidgets.QPushButton(self.centralwidget)
        self.delete.setGeometry(QtCore.QRect(50, 410, 305, 28))
        self.delete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.delete.setStyleSheet("#simpan {\n"
"    background-color: #0078d7; \n"
"    color: white;           \n"
"    border-radius: 10px;        \n"
"    border: none;                \n"
"    padding: 6px 15px;          \n"
"}\n"
"\n"
"#simpan:hover {\n"
"    background-color: #005fa3; \n"
"}\n"
"")
        self.delete.setObjectName("delete")
        self.cari = QtWidgets.QPushButton(self.centralwidget)
        self.cari.setGeometry(QtCore.QRect(290, 134, 71, 28))
        self.cari.setStyleSheet("""
#cari {
    background-color: #0078d7;
    color: white;
    border-radius: 10px;
    border: none;
    padding: 6px 15px;
}
#cari:hover {
    background-color: #005fa3; 
}
""")
        self.cari.setObjectName("cari")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 130, 361, 230))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 5, 0, 0)
        self.formLayout.setHorizontalSpacing(7)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.iDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.iDLabel.setObjectName("iDLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.ID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ID.setMinimumSize(QtCore.QSize(200, 25))
        self.ID.setMaximumSize(QtCore.QSize(200, 25))
        self.ID.setObjectName("ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ID)
        self.namalabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.namalabel.setObjectName("namalabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.namalabel)
        self.stockLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.stockLabel.setObjectName("stockLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stockLabel)
        self.hargalabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hargalabel.setObjectName("hargalabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hargalabel)
        self.kategoriLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kategoriLabel.setObjectName("kategoriLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.kategoriLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.delete.clicked.connect(self.delete_barang)
        self.cari.clicked.connect(self.cari_data)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tambahdatabarang.setText(_translate("MainWindow", "Hapus barang"))
        self.delete.setText(_translate("MainWindow", "Delete"))
        self.cari.setText(_translate("MainWindow", "Cari"))
        self.iDLabel.setText(_translate("MainWindow", "ID"))
        self.namalabel.setText(_translate("MainWindow", "Nama"))
        self.stockLabel.setText(_translate("MainWindow", "Stock"))
        self.hargalabel.setText(_translate("MainWindow", "Harga"))
        self.kategoriLabel.setText(_translate("MainWindow", "Kategori"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
