# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from user import user
import dashboard_admin as da
import dashboard_kasir as dk
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",  
    database="my_oop_database"
)
mycursor = mydb.cursor()

class Ui_MainWindow(object):
    def openAdminDashboard(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def openKasirDashboard(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dk.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def login(self):
        username = self.usn.text()
        password = self.pw.text()
        role = user.login(username, password)
        if role == "admin":
            self.openAdminDashboard()
        elif role == "kasir":
            self.openKasirDashboard()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.setText("Login Failed")
            msg.setInformativeText('Incorrect username or password.')
            msg.setWindowTitle("Error")
            msg.exec_()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 170, 361, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usn = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usn.setObjectName("usn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usn)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.pw = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pw.setObjectName("pw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pw)
        self.Login = QtWidgets.QPushButton(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(47, 300, 305, 28))
        self.Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Login.setStyleSheet("#simpan {\n"
"    background-color: #0078d7; \n"
"    color: white;           \n"
"    border-radius: 10px;        \n"
"    border: none;                \n"
"    padding: 6px 15px;          \n"
"}\n"
"\n"
"#simpan:hover {\n"
"    background-color: #005fa3; \n"
"}\n"
"")
        self.Login.setObjectName("Login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Login.clicked.connect(self.login)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Form Login"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.Login.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
